# Demo: Variables and Tensors (Using Autograd with variables)

In [3]:
# When PyTorch was first introduced, the learnable parameters of your neural network, 
# your model parameters that were tweaked during the training process, were represented using variables.
# Variables were specifically tailored to hold values which
# changed during training of a neural network.

# A variable used to wrap a tensor and had gradients
# enabled and was used with autograd. 


# However, the variable API in PyTorch has been deprecated.
# Variables are no longer needed to work with autograd and to store gradients.
# Everything that a variable used to hold,
# such as the gradient vector, the grad function,
# and so on, is now part of the tensor itself.


# The variable API still exists in PyTorch and you can use it.
# For example, from torch.autograd, you can import the variable module.
import torch
from torch.autograd import Variable

In [33]:
# And you can instantiate a variable as you would earlier.
# Doing this works as expected, but it simply returns a tensor.
var = Variable(torch.FloatTensor([9]))

# So the var variable here holds a tensor, a FloatTensor with size 9.
display(var)
type(var)

tensor([9.])

torch.Tensor

In [34]:
# And really now everything that was true of a variable is true of this tensor.
# Its requires_grad, property is set to false by default,
# and you can turn this on by calling requires_grad_() on it.
display(var.requires_grad)

# turn requires_grad property on.
var.requires_grad_()

False

tensor([9.], requires_grad=True)

In [35]:
# requires_grad_() updares requires_grad property on the tensor,
# that is the variable here, in place.
display(var.requires_grad)

True

In [36]:
# So even though you can use the variable API as you did earlier in PyTorch,
# when you instantiate a variable with requires_grad true,
# what you get is a tensor.

# w1 is a tensor and w2 is a tensor as well.
w1 = Variable(torch.FloatTensor([3]), requires_grad=True)
w2 = Variable(torch.FloatTensor([7]), requires_grad=True)
print(type(w1))
print(type(w2))

display(w1)
display(w2)

<class 'torch.Tensor'>
<class 'torch.Tensor'>


tensor([3.], requires_grad=True)

tensor([7.], requires_grad=True)

In [37]:
# Let's say you multiply these two variables
# instantiated using the variable class, the result will be a tensor.
result_var = var * w1

# So really, variables have just disappeared.
# You only work with tensors now in PyTorch.
# resulting var (here tensor) will have a grad function of MulBackward propagated from the last operation that created it.
result_var

tensor([27.], grad_fn=<MulBackward0>)

In [38]:
# The result grad tensor (result_var) has the grad function MulBackward.
# This is the function that created this tensor and it
# has requires_grad set to true.
result_var.requires_grad

True

In [39]:
# And exactly like we did with tensors earlier,
# calling result_var.backward,
# we'll calculate gradients for all of the input tensors.
result_var.backward()

In [40]:
# w1.grad contains the gradients for w1 with respect to the result var.
w1.grad

tensor([9.])

In [41]:
# W2.grad was not involved in the operations, so there are no gradients here.
w2.grad # not used in computation graph

In [43]:
# And var.grad will contain gradients as well.
var.grad

# So when you're working with PyTorch today, you only work with tensors.
# You don't have to worry about variables.

tensor([3.])