# Demo: Creating and Initializing Tensors

In [1]:
import torch

print(torch.__version__)

1.10.1


In [2]:
# PyTorch's default data type

torch.get_default_dtype()

torch.float32

In [3]:
# TypeError: only floating-point types are supported as the default type (when torch.int is passed as an function argument)
# torch.set_default_dtype(torch.int)

torch.set_default_dtype(torch.float64)

In [4]:
torch.get_default_dtype()

torch.float64

In [7]:
# print the version of CUDA being used by pytorch
print("Cuda Toolkit version:", torch.version.cuda)
print("Cuda available:", torch.cuda.is_available())
print("Cuda device count:", torch.cuda.device_count())

if torch.cuda.is_available():
    curr_device = torch.cuda.current_device()
    print("Cuda current device:", curr_device)
    print("Cuda device name:", torch.cuda.get_device_name(curr_device))
    print("Cuda device properties:", torch.cuda.get_device_properties(curr_device))
    # 7.5
    print("Cuda compute capability:", torch.cuda.get_device_capability(curr_device))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(curr_device)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_reserved(curr_device)/1024**3,1), 'GB')

    torch.cuda.memory_allocated(curr_device)


    # torch.cuda.memory_reserved(curr_device)

Cuda Toolkit version: 11.3
Cuda available: False
Cuda device count: 0


In [8]:
# create a torch tensor by specifiying Python list as its input
# when we use torch.tensor, it is an alias for the default tensor type, namely torch.FloatTensor()
tensor_arr = torch.Tensor([[1, 2, 3], [4, 5, 6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
# check whether the particular python object is a torch tensor
torch.is_tensor(tensor_arr)

True

In [10]:
# get number of elements in torch tensor no matter what its size and shape
torch.numel(tensor_arr)

6

In [11]:
# When you specify torch.Tensor and you only indicate the shape of the tensor, the resulting tensor object will be uninitialized
tensor_uninitialized = torch.Tensor(2, 2)

# this means that behind the scenes PyTorch will allocate the memory for this tensor
# but it won't set up any initial values because you have not specified any
tensor_uninitialized

tensor([[6.1989e-91, 6.5303e-42],
        [6.5495e-43, 8.6044e-43]])

In [12]:
# torch.rand will initialize the tensor with random values,
# this is a quick and easy way to initialize the weights of your model parameters
tensor_initialized = torch.rand(2, 2)
tensor_initialized

tensor([[0.4202, 0.2169],
        [0.1307, 0.2994]])

In [13]:
# int tensor on cpu
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [14]:
# int tensor on gpu
# tensor_int = torch.tensor([5, 3]).type(torch.cuda.IntTensor)
# del tensor_int
# torch.cuda.empty_cache() 

In [15]:
tensor_short = torch.ShortTensor([1, 2, 3])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [16]:
# PyTorch also has support for tensors of type torch.half. This is a floating point tensor which occupies half as much memory
# for each element as a float32, which means these are float16 elements.
tensor_float = torch.tensor([1, 2, 3]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [17]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [18]:
tensor_of_ones = torch.ones((2, 4), dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [19]:
# create the tensor of zeroes in the size, shape and data type of tensor_of_ones
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [20]:
# torch.eye will create two dimensional square matrix with the main diagonal filled with 1s.
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [21]:
# if you already have a tensor instantiated and you want to figure out at what indices the nonzero elements lie, 
# you can call torch.nonzero function.
non_zero = torch.nonzero(tensor_eye)
# will show [i, j] indices of non-zero elements
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [22]:
# torch.tensor() always makes a copy of the underlying data of the tensor
# torch.tensor() can be used to copy existing tensor or numpy array or list.
# torch.tensor infers the dtype automatically, while torch.Tensor returns a torch.FloatTensor.
# I would recommend to stick to torch.tensor, which also has arguments like dtype, if you would like to change the type.
i = torch.tensor([[0, 1, 1], 
                  [2, 2, 0]])

i

tensor([[0, 1, 1],
        [2, 2, 0]])

In [23]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)
v

tensor([3., 4., 5.], dtype=torch.float32)

In [24]:
# tensors i and v above are dense tensors; all of the elements have usually nonzero values.
# PyTorch also has a support for sparse tensors which are very commonly used. When you build your machine learning models,
# your data may not always be dense, it would be sparse data and you might want to use a sparse tensor.
# The sparse_coo_tensor function constructs a sparse tensor in coordinate format. The non-zero elements are at the indices
# that you specify that is i, with the given values that you specified, which is the variable v. The resulting sparse tensor is
# of shape 2, 5.

# The tensor i that we had instantiated earlier specifies the indices at which sparse tensor contains data. And the tensor v 
# specifies the values contained in the sparse tensor.
sparse_tensor = torch.sparse_coo_tensor(i, v, (2, 5))
print(sparse_tensor)


# Every PyTorch tensor has the .data variable, which you can use to access the underlying matrix.
print(sparse_tensor.data)


# To see what its dense equivalent contains
# Unspecified elements in sparse_tensor are assumed to have the same value, fill value, which is zero by default.
# (0, 2) => 3, (1, 2) => 4, (1, 0) => 5; the rest will be zero
sparse_tensor.to_dense()

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)
tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)


tensor([[0., 0., 3., 0., 0.],
        [5., 0., 4., 0., 0.]], dtype=torch.float32)

In [25]:
# Another example for sparse tensors
indices = torch.tensor([[0, 1, 2, 0, 2],
                        [0, 1, 2, 2, 0]])
# print(indices.shape)

# Seed everything
# seed = 7
# random.seed(seed)
# np.random.seed(seed)
# torch.manual_seed(seed)
# torch.cuda.manual_seed_all(seed)

# https://pytorch.org/docs/stable/generated/torch.randint.html
values = torch.tensor([89, 21, 33, 57, 94])
s = torch.sparse_coo_tensor(indices, values, (4, 5))
print(s)
print(s.to_dense())

tensor(indices=tensor([[0, 1, 2, 0, 2],
                       [0, 1, 2, 2, 0]]),
       values=tensor([89, 21, 33, 57, 94]),
       size=(4, 5), nnz=5, layout=torch.sparse_coo)
tensor([[89,  0, 57,  0,  0],
        [ 0, 21,  0,  0,  0],
        [94,  0, 33,  0,  0],
        [ 0,  0,  0,  0,  0]])


# Demo: Simple Operations on Tensors

In [12]:
initial_tensor = torch.rand(2, 3)

initial_tensor

tensor([[0.6623, 0.1780, 0.1433],
        [0.5077, 0.3822, 0.5270]])

In [35]:
# Operations (functions) that modify the tensor in-place have an "_" suffix
initial_tensor.fill_(10)

initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [13]:
initial_tensor[0]

tensor([0.6623, 0.1780, 0.1433])

In [14]:
# there is no corresponding out-of-place fill operation
initial_tensor.fill(10)

AttributeError: 'Tensor' object has no attribute 'fill'

In [27]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [36]:
# add 5 to every element of the initial tensor, this is out-of_place operation
new_tensor = initial_tensor.add(5)
print("new:\n", new_tensor)
print("initial:\n", initial_tensor)

new:
 tensor([[15., 15., 15.],
        [15., 15., 15.]])
initial:
 tensor([[10., 10., 10.],
        [10., 10., 10.]])


In [37]:
# in-place add operation with _ suffix. Will modify initial_tensor itself.
initial_tensor.add_(8)

initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [38]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [39]:
# in-place square root operation
new_tensor.sqrt_()

new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [54]:
# You will find that a number of operations which are very similar to Numpy are available with torch tensors as well.
# such as torch.linspace will generate evenly spaced numbers between 0.1 and 10 here.

x = torch.linspace(start=0.1, end=10.0, steps=15)
print(len(x))
print(type(x))
print(x.type())
print(x)

15
<class 'torch.Tensor'>
torch.DoubleTensor
tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])


In [55]:
# We will use torch.chunk to chunk our x tensor into three separate parts, it is out-of-place operation, 
# no "_" suffix at the end.
# funtion signature: torch.chunk(input, chunks, dim=0) → List of Tensors.
# input (Tensor) – the tensor to split
# chunks (int) – number of chunks to return
# dim (int) – dimension along which to split the tensor

tensor_chunk = torch.chunk(x, 3, 0)

print(type(tensor_chunk))

# a tuple of 3 separate tensors of length 5 each
tensor_chunk

<class 'tuple'>


(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [59]:
# You can use torch.cat to concatenate tensors
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3., 4., 5.])

# concatenate on dim = 0. all other dimensions must have the same shape except for the concatenating dimension.
torch.cat((tensor1, tensor2, tensor3), dim=0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [6]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])

random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [70]:
# You can use the square bracket notation to index into Pytorch tensors to access specific elements.
# obtain element and row i and column j.
# observe that indexing into PyTorch tensor gives us a tensor as the result.
random_tensor[0, 1]

tensor(8.)

In [71]:
# for multi-dimensional tensors len() returns the first dimension's size
print(len(random_tensor), "\n")

# go over all rows and cols in tensor
for i in range(0, len(random_tensor)):
    for j in range(0, len(random_tensor[i])):
        print(random_tensor[i, j])

3 

tensor(10.)
tensor(8.)
tensor(30.)
tensor(40.)
tensor(5.)
tensor(6.)
tensor(12.)
tensor(2.)
tensor(21.)


In [74]:
# You can also use tensors with array slicing operations as you would with Numpy.

# Here we are accessing all of the rows from row 1 onwards and all of the columns from column 1 onwards
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [85]:
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [84]:
# The .size function on a tensor will give us the size of tensor along each of its dimensions. 
# Return value is of type torch.Size
print(type(random_tensor.size()))
random_tensor.size()

<class 'torch.Size'>


torch.Size([3, 3])

In [7]:
# Tensor.view(*shape) → Tensor
# parameters: shape (torch.Size or int...) – the desired size

# If you want to view a particular tensor using a different shape, you can use the view function.
# Be mindful that the view function does NOT create a new tensor, it uses the same underlying memory as the original tensor.
# view() reshapes the tensor without copying memory, similar to numpy's reshape().
resized_tensor = random_tensor.view(9) # view it as a 1-D tensor with 9 elements

resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [8]:
resized_tensor.size()

torch.Size([9])

In [9]:
# Let's now satisfy ourselves that the original tensor and our view of it share the same underlying memory.
random_tensor[2, 2] = 100;

print(random_tensor)
print(resized_tensor)

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])
tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])


In [95]:
# Just like with Numpy arrays, a quick way to view the shape of a particular tensor is to call tensor.shape.
# returns the same result as we call size() function
print(random_tensor.shape)
print(resized_tensor.shape)

torch.Size([3, 3])
torch.Size([9])


In [96]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [101]:
# You can change the shape of a tensor in PyTorch by removing and adding dimensions using squeeze and unsqueeze operations.
# unsqueeze operation that will add an additional dimension to the random_tensor
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)

# it made the tesnor to have shape of 3 x 3 x 1
print(tensor_unsqueeze.shape)

# new dimension is added at index 2, which will be the inner most dimension.
tensor_unsqueeze

torch.Size([3, 3, 1])


tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [102]:
# let's make create tensor of shape 3 x 1 x 3 from random_tensor

tensor_unsqueeze1 = torch.unsqueeze(random_tensor, 1)
print(tensor_unsqueeze1.shape)

tensor_unsqueeze1

torch.Size([3, 1, 3])


tensor([[[ 10.,   8.,  30.]],

        [[ 40.,   5.,   6.]],

        [[ 12.,   2., 100.]]])

In [103]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [106]:
# Let's now perform a transpose operation which will allow use to flip dimensions in this tensor
tensor_transpose = torch.transpose(initial_tensor, 0, 1)

# now we have 3 x 2 tensor, transposed from 3 x 2 tensor.
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

# Demo: Elementwise and Matrix Operations on Tensors

In [10]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [11]:
# It is possible for you to sort your tensors based on the values on its elements by calling torch.sort.
# It returns a named tuple of (values, indices), where values are the sorted values and indices 
# are the indices of the elements in the original input tensor.
# You can, in addition, specify a dimension along which you want your tensor sorted.
# If dim parameter is not given, the last dimension of the input is chosen. By default dim=-1.

# here the tensor will be sorted along the dim = 1 which is its last dimension, in other words it will be sorted along the row.
# dim = 1 means, sorts the valus in columns along the row.
# dim = 0 means, sorts the values in rows along a column.
sorted_tensor, sorted_indices = torch.sort(random_tensor)

print(sorted_tensor)

# sorted indices will give you index positions from the original tensor, but in a sorted order. 
# Indices are column indices obtained from original tensor showing the original index of the sorted value.
print(sorted_indices)

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])
tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])


In [5]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])

tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [6]:
# torch.abs  for absolute values
tensor_abs = torch.abs(tensor_float)

tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [7]:
# torch.randn() Returns a tensor filled with random numbers from a normal distribution with
# mean 0 and variance 1 (also called the standard normal distribution).

rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

print(rand1)
print(rand2)

tensor([[1.0481, 0.5333, 0.3703],
        [0.6363, 0.1609, 0.6487]])
tensor([[1.6744, 0.1938, 2.3027],
        [0.8423, 0.1649, 1.0542]])


In [8]:
# elementwise addition of two matrices (tensors)
add1 = rand1 + rand2

add1

tensor([[2.7225, 0.7271, 2.6730],
        [1.4785, 0.3258, 1.7030]])

In [9]:
# There are of course torch functions available for all kinds of mathematical operations
add2 = torch.add(rand1, rand2)

add2

tensor([[2.7225, 0.7271, 2.6730],
        [1.4785, 0.3258, 1.7030]])

In [12]:
tensor = torch.Tensor([[-1, -2, -3],
                      [1, 2, 3]])

tensor

tensor([[-1., -2., -3.],
        [ 1.,  2.,  3.]])

In [15]:
# add 0.3 to every element of the tensor, however original tensor is untouched
print(tensor + 0.3)

print(tensor)

tensor([[-0.7000, -1.7000, -2.7000],
        [ 1.3000,  2.3000,  3.3000]])
tensor([[-1., -2., -3.],
        [ 1.,  2.,  3.]])


In [17]:
# use torch.div operation to perform elementwise division
tensor_div = torch.div(tensor, tensor + 0.3)

tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [18]:
# Elementwise multiplication
tensor_mul = torch.mul(tensor, tensor)

tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [19]:
# A very useful operation performed on a tensor, which is often used you are building machine learning models 
# is the clamp operation. It clamps all elements in input into the range [ min, max ].

tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)

# all values smaller then min will be replaced by min, all value greater than max will be replaced by max
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [20]:
# In addition to element-wise operations, you can also perform matrix operations on PyTorch Tensors.

# torch.Tensor() is a constructor for creating a new tensor object in PyTorch. When you pass a list of values to 
# this constructor, it creates a 1-dimensional tensor containing the provided values
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

print(t1)
print(t2)

tensor([1., 2.])
tensor([10., 20.])


In [21]:
# The torch.dot function allows to calculate the dot_product of these two matrices.
dot_product = torch.dot(t1, t2)

dot_product

tensor(50.)

In [23]:
# multidimensional tensor which is a matrix
matrix = torch.Tensor([[1, 2, 3],
                      [4, 5, 6]])

# single dimensional tensor which is a vector
vector = torch.Tensor([0, 1, 2])

print(matrix)
print(vector)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([0., 1., 2.])


In [25]:
# torch.mv will multiply the matrix by the corresponding vector. For multiplication, the number of columns of the first tensor
# should be equal to the size of seconf tensor (if it is a vector) or the number of rows in the second tensor 
# (if it is a matrix)
# for example if you multiple 2x3 matrix with 3x1 matrix, you will obtain 2x1 matrix as a result. If one is its dimensions 
# become 1, then resulting tensor will still be vector.
# Respective elements will be multiplied.

# their shapes should be compatible; the number of elements in our vector is compatible with the number of elements
# in the second dimension of our matrix.

# resulting matrix: [[1 * 0 + 2 * 1 + 3 * 2],
#                    [4 * 0 + 5 * 1, 6 * 2]]
# which is [[8],
#          [17]] and can be considered as [8, 17].
matrix_vector = torch.mv(matrix, vector)

matrix_vector

tensor([ 8., 17.])

In [26]:
# You can use torch.mm operation if you want to perform a matrix multiplication between two matrices

another_matrix = torch.Tensor([[10, 30],
                               [20, 0],
                               [0, 50]])

# another_matrix has a shape of 3x2 which is compatible with matrix's shape 2x3, the number of elements in the second dimension
# of the first matrix should be equal to the number of elements in the first dimennsion of the second matrix.
# multiplication happens like this row1_matrix1 * column1_matrix2, row1_matrix1 * column2_matrix2, etc...
matrix_mul = torch.mm(matrix, another_matrix)

matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

In [27]:
# The torch.argmax function will find you the largest element along a particular dimension
# returns the indices of the maximum values of a tensor across a dimension.
# If dim = 1, we will look at the columns in the following matrix along each row.
# returns an indice of max value at the given particular dimension, in our case 180 - 1, 420 - 1. 1 means second column.
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [28]:
# now lets consider dim=0
# max values along dim=0, are 140 - 1, 420 - 1. 1 means second row.
torch.argmax(matrix_mul, dim=0)

tensor([1, 1])

In [29]:
matrix_mul2 = torch.mm(another_matrix, matrix)

matrix_mul2

tensor([[130., 170., 210.],
        [ 20.,  40.,  60.],
        [200., 250., 300.]])

In [30]:
# max values along dim=0 are 200 - 2, 250 - 2, 300 - 2. 2 means 3rd row.
torch.argmax(matrix_mul2, dim=0)

tensor([2, 2, 2])

In [31]:
# max values along dim=1 are 210 - 2, 60 - 2, 300 - 2. 2 means 3rd column.
torch.argmax(matrix_mul2, dim=1)

tensor([2, 2, 2])

In [32]:
# Similarly torch.argmin will give you the index of the smallest element along a particular dimension

# 50 - 0, 180 - 0; 0 - first row.
print(torch.argmin(matrix_mul, dim=0))
# 50 - 0, 140 - 0; 0 - first column.
print(torch.argmin(matrix_mul, dim=1))

# 20 - 1, 40 - 1, 60 - 1; 1 - second row
print(torch.argmin(matrix_mul2, dim=0))
# 130 - 0, 20 - 0, 200 - 0; 0 - first column.
print(torch.argmin(matrix_mul2, dim=1))

tensor([0, 0])
tensor([0, 0])
tensor([1, 1, 1])
tensor([0, 0, 0])
