# Demo: Dynamic Computation Graphs in Tensorflow with Eager Execution

Until about the end of 2017, TensorFlow only supported static computation graphs,
which worked, as we saw in an earlier demo.
Contributors to TensorFlow soon realized that dynamic
computation graphs were far easier when you wanted to quickly prototype your neural network models, 
which is why they added dynamic computation graph support to TensorFlow,
and this is available using something called eager execution,
the imperative programming environment in TensorFlow that
evaluates operations immediately without you having to define a
static computation graph and then running it.
The combination of eager execution,
along with the Keras high-level API to build your models, makes PyTorch and TensorFlow very close.
It's hard to choose between them.

In [1]:
# Let's go ahead and import the numpy, as well as the tensorflow libraries.

import numpy as np
import tensorflow as tf

In [2]:
# In order to use TensorFlow in eager execution mode,
# eager execution should be enabled at the very start of your program or session.
# The mode has to be set up front before you write any lines of TensorFlow code.

tf.enable_eager_execution()

In [3]:
# You can check to see whether TensorFlow is in the eager
# execution mode by calling tf.executing_eagerly().

tf.executing_eagerly()

True

In [4]:
# Let's create the same computation graph that we had worked with earlier.
# We have W, x, and b,
# and I want to calculate y is equal to W multiplied by x plus b.
# Notice that W and b are both variables and x is a constant.
# Now placeholders do not work in eager execution mode,
# so you can only use variables and constants.
# This should intuitively make sense because if you're
# executing as you build your graph,
# you don't really need a placeholder to feed in data at the time of execution.

W = tf.Variable(6, name = 'var_W')
x = tf.constant([10, 20, 30], name = 'x')
b = tf.Variable(3, name = 'constant_b')

In [6]:
# W is a variable and earlier we could not view the contents of W without
# running a variables initializer within a session.
# But in eager execution mode, you can view all of the details of W,
# as well as the current value that it's initialized to.
# The initialization of W happens right away when you're in eager execution mode.

W

<tf.Variable 'var_W:0' shape=() dtype=int32, numpy=6>

In [7]:
# You can see that x are constant also has its value assigned.
# All of the other details are visible, along with the current value of x.

x

<tf.Tensor: id=8, shape=(3,), dtype=int32, numpy=array([10, 20, 30])>

In [8]:
# The same is true for the other variable that we instantiated.
# We did not need to run the variable initializer in order to view its contents,
# in order for the contents to be assigned to the variable.

b

<tf.Variable 'constant_b:0' shape=() dtype=int32, numpy=3>

In [9]:
# Let's now perform our operation y is equal to W multiplied by x plus b.
y = W * x + b # Earlier this just defined the computation graph,


# now if you take a look at the value of y,
# you'll find that the computation graph was executed as well.
# In eager execution mode,
# the final calculated value for y is available right there for you.
# So the computation graph was executed as we defined it.
y

<tf.Tensor: id=23, shape=(3,), dtype=int32, numpy=array([ 63, 123, 183])>

In [11]:
# If you print out the value of y,
# you'll see that it's an integer tensor with the value 63 63.
print(y)

tf.Tensor([ 63 123 183], shape=(3,), dtype=int32)


In [12]:
# Exactly like with PyTorch,
# you can print out intermediate values by performing calculations on the fly.
print(W*x)

tf.Tensor([ 60 120 180], shape=(3,), dtype=int32)


In [14]:
# Now in eager execution mode,
# the behavior of the TensorFlow graphs are very similar to graphs in PyTorch.
# When you're running in eager execution mode in TensorFlow,
# you can also perform NumPy operations on your tensors.

# np.multiply will multiply W and x.
# And you can see that the result here of our NumPy
# multiplication operation is a NumPy array of tensors.
np_result = np.multiply(W, x)

np_result

array([<tf.Tensor: id=37, shape=(), dtype=int32, numpy=60>,
       <tf.Tensor: id=40, shape=(), dtype=int32, numpy=120>,
       <tf.Tensor: id=43, shape=(), dtype=int32, numpy=180>], dtype=object)

In [15]:
# Just like with PyTorch,
# you can now access the underlying numpy array associated with any tensor,
# by calling W.numpy.
# Here is the numpy array associated with W.

W.numpy()

6

In [16]:
# and y.numpy will give you the corresponding numpy array.
y.numpy()

array([ 63, 123, 183])

In [17]:
type(W.numpy())

numpy.int32

In [18]:
type(y.numpy())

numpy.ndarray

# Debugging in PyTorch

Before we complete this module, let's quickly talk about how debugging works in PyTorch.
You'll find that debugging in PyTorch is just like debugging Python.
You can use pdb, breakpoints, everything that you do with normal Python code,
you can use with PyTorch.
This is not true in the case of debugging TensorFlow programs.
If you're working with Python, pdb is a standard Python debugger that you use,
even for normal Python code,
and this is the same thing which can be used with PyTorch.
The backward pass through your neural network where you compute
gradients and tweak model parameters can also be debugged by
instrumenting your code with pdb.set_trace().
Using pdb, you can step through the forward,
as well as the backward passes, in the training of your neural network.

# Debugging in TensorFlow

On the other hand, debugging TensorFlow is actually quite hard,

and there is an entire course on debugging TensorFlow applications on Pluralsight.

There are different ways to debug.

You can fetch tensors using session.run(),

you can print tensors using special operations like tf.Print(),

you can use tf.Assert statements,

you can interpose Python code using tf.py_func() into your TensorFlow execution,

or you can use a special debugger called tfdbg.

Because the TensorFlow static computation graph involves

instantiating a session environment, you need this special debugger.

Ordinary Python debuggers do not allow you to debug the training

phase of the neural network in TensorFlow.